@startuml

abstract class AbstractProduct{
    m1()
}
note left of AbstractProduct: 抽象产品类，\n可以是抽象类，\n也可以是接口
class ProductA1{
    m1()
}
class ProductA2{
    m1()
}
class ProductB1{
    m1()
}
class ProductB2{
    m1()
}

interface AbstractFactory{
    AbstractProduct createProduct()
}
class AFactory{
    AbstractProduct createProduct()
}
class BFactory{
    AbstractProduct createProduct()
}

AbstractFactory <|.. AFactory
AbstractFactory <|.. BFactory
AFactory ..> ProductA1
AFactory ..> ProductA2
BFactory ..> ProductB1
BFactory ..> ProductB2

ProductA1 --|> AbstractProduct
ProductA2 --|> AbstractProduct
ProductB1 --|> AbstractProduct
ProductB2 --|> AbstractProduct

@enduml