@startuml

class GraphicsEditor{
    draw(Shape);
    drawCircle();
    drawRectangle();
    drawShape();
}
note right of GraphicsEditor
draw(Shape shape){
    if(shape.type == Circle.type){
        drawCircle();
    }else if(shape.type == Rectangle.type){
        drawRectangle();
    }else{
        drawShape();
    }
};
end note
class Circle
class Rectangle
class Shape{
    int type;
}

GraphicsEditor --> Circle
GraphicsEditor --> Shape
GraphicsEditor --> Rectangle
Shape <|-- Circle
Shape <|-- Rectangle

@enduml