@startuml

interface Eatable{
    void eat()
}

interface Flyable{
    void fly()
}

interface Swimable{
    void swim()
}

class Dog{
    void eat()
    void swim()
}

class Bird{
    void eat()
    void fly()
}

Eatable <|-- Dog
Swimable <|-- Dog
Eatable <|-- Bird
Flyable <|-- Bird

@enduml